on:
  push:
    tags:
      - "**"

jobs:
  build:
    name: ${{ matrix.os.family }}
    runs-on: ${{ matrix.os.name }}-latest
    strategy:
      matrix:
        os:
          - name: ubuntu
            family: linux
          - name: windows
            family: windows
          - name: macos
            family: darwin
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/checkout@v4
      - run: |
          pip install pyqt5
          pip install --target libs/${{ matrix.os.family }} --upgrade pyeodh
          python deploy.py --dist dist/eodh_qgis

      - if: ${{ matrix.os.name != 'windows' }}
        run: |
          cd dist
          zip -r eodh_qgis_${{ github.ref_name }}_${{ matrix.os.family }}.zip eodh_qgis

      - if: ${{ matrix.os.name == 'windows' }}
        run: |
          cd dist
          Compress-Archive -Path 'eodh_qgis' -DestinationPath 'eodh_qgis_${{ github.ref_name }}_${{ matrix.os.family }}.zip'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.family }}
          path: dist/eodh_qgis_${{ github.ref_name }}_${{ matrix.os.family }}.zip

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - run: gh release create ${{ github.ref_name }} artifacts/*.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
