name: Release
on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install pyqt5
          pip install --target libs --upgrade pyeodh

      - name: Build release
        run: |
          python deploy.py --dist dist/eodh_qgis
          cd dist
          zip -r eodh_qgis_${{ github.ref_name }}.zip eodh_qgis

      - name: Create release
        run: gh release create ${{ github.ref_name }} dist/eodh_qgis_${{ github.ref_name }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
