name: Release
on:
  push:
    tags:
      - "**"

jobs:
  install-libs:
    name: ${{ matrix.os.family }}
    runs-on: ${{ matrix.os.name }}-latest
    strategy:
      matrix:
        os:
          - name: ubuntu
            family: linux
          - name: windows
            family: windows
          - name: macos
            family: darwin
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libs
        run: |
          pip install --target libs/${{ matrix.os.family }} --upgrade pyeodh

      - name: Zip libs for Linux/macOS
        if: ${{ matrix.os.name != 'windows' }}
        run: |
          zip -r libs_${{ matrix.os.family }}.zip libs

      - name: Zip libs for Windows
        if: ${{ matrix.os.name == 'windows' }}
        run: |
          Compress-Archive -Path 'libs' -DestinationPath 'libs_${{ matrix.os.family }}.zip'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libs_${{ matrix.os.family }}
          path: libs_${{ matrix.os.family }}.zip

  build-release:
    runs-on: ubuntu-latest
    needs: [install-libs]
    permissions:
      contents: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install pyqt5

      - name: Download libs artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Unzip libs
        run: |
          unzip -o artifacts/libs_linux.zip
          unzip -o artifacts/libs_windows.zip
          unzip -o artifacts/libs_darwin.zip

      - name: Build release
        run: |
          python deploy.py --dist dist/eodh_qgis
          cd dist
          zip -r eodh_qgis_${{ github.ref_name }}.zip eodh_qgis

      - name: Create release
        run: gh release create ${{ github.ref_name }} eodh_qgis_${{ github.ref_name }}.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
